server:
  port: 8080
spring:
  application:
    name: "MSAuthentication"
  devtools:
    add-properties: false
  profiles:
    include: null
  #r2dbc:
  #  schema:
  #    create-mode: "always"
  #    locations: "classpath:schema.sql"
  sql:
    init:
      mode: "always"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    users: "/api/v1/usuarios"
    userById: "/api/v1/usuario/{id}"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "postgres"
    schema: "public"
    username: "postgres"
    password: "postgres"
